# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b117a1d22265e9e6ea6cdaf0f65bcf64f351b442b7f01fb467a69de764205df03309175274078e9fbf4f16222f1fcc226282bfd367bdf3b1d470e015312f7238

test:
  secret_key_base: f20dcc4e92b83082aee6ee60fa19e761a55dd50b2ef88d35bc7c0ef17fc029b9ba1b8e3e8225fa531eaed7405d92c49d14772bf02befc3547dbe67ac73bf3fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
